# FILE: environment.yml

name: dialogue-summarization
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.4
  - scipy=1.15.2
  - pytorch-lightning=2.2.2
  - torchmetrics
  - pillow
  - pip
  - pip:
      - hydra-core
      - wandb
      - transformers==4.41.2
      - tokenizers>=0.13.0
      - datasets>=2.12.0
      - accelerate>=0.20.0
      - sentencepiece
      - scikit-learn
      - lightning>=2.0.0
      - omegaconf>=2.3.0
      - tensorboard
      - rouge-score>=0.1.2
      - rouge-metric
      - nltk>=3.8.0
      - konlpy>=0.6.0
      - mecab-python3>=1.0.6
      - python-mecab-ko>=1.3.0
      - python-dotenv>=1.0.0
      - pathlib2
      - typing-extensions>=4.5.0
      - fire>=0.5.0
      - icecream>=2.1.0
      - click
      - rich
      - pandas
      - pyyaml
      - tqdm
      - pre-commit
      - matplotlib
      - seaborn==0.13.2
      - rouge-score
      