name: dialogue-summarization
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.10.13

  # PyTorch ecosystem with CUDA 12.4 support (compatible with CUDA 12.2)
  - pytorch=2.5.1=*cuda*  # Force CUDA version, not CPU
  - torchvision=*=*cu124*  # CUDA 12.4 version
  - torchaudio=*=*cu124*   # CUDA 12.4 version
  - pytorch-cuda=12.4      # CUDA 12.4 is compatible with driver 12.2

  # Core ML libraries via conda
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0

  # Development tools via conda
  - jupyter
  - ipykernel
  - black
  - isort
  - pytest
  - pre-commit

  # System utilities
  - pyyaml
  - tqdm
  - click
  - rich

  # Pip-only dependencies
  - pip
  - pip:
    # Hugging Face ecosystem
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - datasets>=2.12.0
    - accelerate>=0.20.0

    # PyTorch Lightning
    - pytorch-lightning>=2.0.0
    - lightning>=2.0.0
    - torchmetrics>=0.11.0

    # Configuration management
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0

    # Experiment tracking
    - wandb>=0.15.0
    - tensorboard

    # Evaluation metrics
    - rouge-score>=0.1.2
    - nltk>=3.8.0

    # Korean NLP support
    - konlpy>=0.6.0
    - mecab-python3>=1.0.6
    - python-mecab-ko>=1.3.0

    # Utilities
    - python-dotenv>=1.0.0
    - pathlib2
    - typing-extensions>=4.5.0

    # CLI and debugging utilities
    - fire>=0.5.0           # Google Fire for easy CLI interfaces
    - icecream>=2.1.0       # Better debugging with ic()