# FILE: configs/preprocessing/default_preprocessing.yaml
# @package preprocessing
# Preprocessing configuration for text generation
strategy: "std"
max_input_length: 512
max_target_length: 60
truncation: true
padding: false
normalize_whitespace: true
remove_extra_newlines: true
special_tokens:
  - "#Person1#"
  - "#Person2#"
  - "#Person3#"
  - "#Person4#"
  - "#Person5#"
  - "#Person6#"
  - "#Person7#"
  - "#PhoneNumber#"
  - "#Address#"
  - "#PassportNumber#"