# @package _global_
# Standard preprocessing configuration for dialogue summarization

preprocessing:
  # Processing strategy name
  strategy: "std"
  
  # Text cleaning options
  normalize_whitespace: true
  remove_extra_newlines: true
  
  # Tokenization settings
  max_input_length: 512
  max_target_length: 128
  truncation: true
  padding: "max_length"
  
  # ✅ CORRECTED: Special tokens matching the dataset format
  special_tokens:
    - "#Person1#"
    - "#Person2#"
    - "#Person3#"
    - "#PhoneNumber#"
    - "#Address#"
    - "#PassportNumber#"