# FILE: configs/preprocessing/standard.yaml
# @package preprocessing
# Standard preprocessing configuration for dialogue summarization
# preprocessing:
  # Processing strategy name
strategy: "std"

# ✅ FIX: Add max_length values to the standard preprocessing config
max_input_length: 512
max_target_length: 120

# Tokenization and cleaning settings
truncation: true
padding: false
normalize_whitespace: true
remove_extra_newlines: true

token_swapping:
  enable: true
  token_map:
    "#Person1#": "민준"
    "#Person2#": "서연"
    "#Person3#": "지훈"
    "#Person4#": "수진"
    "#Person5#": "현우"
    "#Person6#": "은영"
    "#Person7#": "동현"
  additional_special_tokens: ["민준", "서연", "지훈", "수진", "현우", "은영", "동현"]

# Special tokens to be added to the tokenizer
special_tokens:
  additional_special_tokens:
    - "#Person1#"
    - "#Person2#"
    - "#Person3#"
    - "#Person4#"
    - "#Person5#"
    - "#Person6#"
    - "#Person7#"
