# FILE: configs/dataset/dialogue_data.yaml
# @package dataset
# Dataset configuration for Korean dialogue summarization

# Data paths
data_path: "/home/wb2x/workspace/dialogue-summarizer/data"

# File names
files:
  train: "train.csv"
  dev: "dev.csv"
  test: "test.csv"
  submission_template: "sample_submission.csv"

# Column mappings
columns:
  id: "fname"
  input: "dialogue"
  target: "summary"
  topic: "topic"

# ✅ BASELINE BATCH SIZES: Exact match
batch_size: 50              # per_device_train_batch_size from baseline
eval_batch_size: 32         # per_device_eval_batch_size from baseline
shuffle_train: true
shuffle_val: false
drop_last: false

# Data splits (using provided train/dev split)
use_provided_split: true
train_split_ratio: null
val_split_ratio: null

# Submission format
submission:
  format: "indexed_csv"
  columns: ["fname", "summary"]
  include_index: true
  index_name: ""

# Data validation
validate_files: true
check_encoding: true
sample_size_check: true

# Statistics (computed during loading)
stats:
  train_size: null
  dev_size: null
  test_size: null
  avg_input_length: null
  avg_target_length: null