# @package training
# Performance-oriented training configuration for a SINGLE GPU

# Training strategy
strategy: "auto"             # ◀️ REVERTED: 'auto' is best for a single GPU
accelerator: "auto"
devices: 1                   # ◀️ REVERTED: Target your single available GPU
precision: "16-mixed"

# Epochs and steps
max_epochs: 20
max_steps: -1
min_epochs: 1

# Batch sizes
# Effective batch size is 16 * 2 = 32. Your 24GB GPU can handle this well.
batch_size: 16
eval_batch_size: 16
accumulate_grad_batches: 2

# Optimizer
optimizer:
  name: "adamw"
  lr: 1e-5              # ← REDUCED from 5e-5
  weight_decay: 0.01    # ← REDUCED from 0.05
  betas: [0.9, 0.999]
  eps: 1.0e-8

# Learning rate scheduler
lr_scheduler:
  name: "cosine"
  warmup_ratio: 0.1
  warmup_steps: null
  max_lr: ${training.optimizer.lr}
  min_lr: 1.0e-7

# Validation and evaluation
val_check_interval: 1.0
check_val_every_n_epoch: 1
evaluation_strategy: "epoch"
predict_with_generate: true

# Generation settings for validation
generation:
  max_length: 100        # ← INCREASED from 64
  min_length: 1          # ← DECREASED from 15 
  num_beams: 1           # ← CHANGED to greedy (like peer)
  no_repeat_ngram_size: 3 # ← INCREASED from 2
  early_stopping: false  # ← DISABLED (required with num_beams=1)
  do_sample: false
  length_penalty: 1.2    # ← ADDED length penalty
  repetition_penalty: 1.1 # ← ADDED to reduce repetition

# Model saving
save_strategy: "epoch"
save_total_limit: 5
save_top_k: 3
monitor: "val/rouge_f"
mode: "max"
save_on_train_epoch_end: false

# Early stopping
early_stopping:
  enabled: true
  monitor: "val/rouge_f"
  patience: 3
  min_delta: 0.001
  mode: "max"
  verbose: true

# Gradient settings
gradient_clip_val: 1.0
gradient_clip_algorithm: "norm"

# Logging
log_every_n_steps: 100 # LOG SPAM
# logging_strategy: "epoch"

# Memory optimization
dataloader_num_workers: 16  # 🚀 CHANGED: Increased based on your 32-core CPU to speed up data loading
dataloader_pin_memory: true
persistent_workers: true

# Mixed precision
amp_backend: "native"
amp_level: "O1"

# Debugging
fast_dev_run: false
overfit_batches: 0.0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0

# Profiler
profiler: null  # Options: null, "simple", "advanced", "pytorch"

# Reproducibility settings
deterministic: false  # Set to true for full reproducibility (may slow training)
benchmark: true       # Set to false if input sizes vary significantly

# Resume training
resume_from_checkpoint: null
auto_resume: false