# @package postprocessing
# Post-processing configuration for text generation

# Token removal settings
remove_tokens:
  - "<usr>"
  - "<s>"
  - "</s>"
  - "<pad>"
  - "<unk>"
  - "<bos>"
  - "<eos>"

# Text cleaning settings
text_cleaning:
  strip_whitespace: true
  normalize_whitespace: true
  remove_empty_lines: true
  remove_extra_spaces: true

  # ✅ NEW: Clean up extra colons and punctuation
  clean_extra_colons: true
  clean_repeated_punctuation: true  

# Korean-specific cleaning
korean_specific:
  remove_special_markers: true   # ✅ REMOVE #Person# for clean output
  normalize_punctuation: true

# Advanced cleaning
advanced:
  min_length: 10
  max_repetition_ratio: 0.3
  remove_repetitive_phrases: true
  # ✅ NEW: Clean up dialogue formatting issues
  clean_dialogue_artifacts: true