# FILE: configs/postprocessing/default_postprocessing.yaml
# @package postprocessing
# Postprocessing configuration for text generation
skip_special_tokens: false
remove_tokens:
  - "<usr>"
  - "<s>"
  - "</s>"
  - "<pad>"
  - "<unk>"
text_cleaning:
  strip_whitespace: true
  normalize_whitespace: true
  remove_empty_lines: true
korean_specific:
  remove_special_markers: false
  normalize_punctuation: true