# FILE: configs/postprocessing/swap_unbiased_speaker.yaml
# @package postprocessing
# Post-processing configuration for text generation


token_swapping:
  enable: true
  token_map:
    "#Person1#": "화자1"
    "#Person2#": "화자2"
    "#Person3#": "화자3"
    "#Person4#": "화자4"
    "#Person5#": "화자5"
    "#Person6#": "화자6"
    "#Person7#": "화자7"
remove_tokens:
  - "<usr>"
  - "<s>"
  - "</s>"
  - "<pad>"
  - "<unk>"

# Advanced cleaning
advanced:
  min_length: 10
  max_repetition_ratio: 0.3
  remove_repetitive_phrases: true
  # ✅ NEW: Clean up dialogue formatting issues
  clean_dialogue_artifacts: true