# @package postprocessing
# Training postprocessing - minimal cleaning to preserve learning

remove_tokens:
  - "<usr>"
  - "<pad>"
  - "<unk>"
  # ✅ Keep <s>, </s> and #Person# tokens for training

text_cleaning:
  strip_whitespace: true
  normalize_whitespace: true
  remove_empty_lines: false
  remove_extra_spaces: true

korean_specific:
  remove_special_markers: false  # ✅ Keep all markers during training

advanced:
  min_length: 1  # ✅ No